import AppLayout from '@/Layouts/AppLayout';
import { router, useForm, usePage } from '@inertiajs/react';
import { useMemo, useState } from 'react';
import type { FinanceProps, PaymentRow } from './types';

const formatCurrency=(amount:number)=>`${new Intl.NumberFormat('fr-FR').format(Math.round(amount||0))} FCFA`;
const formatDate=(date:string)=>date;
const emptyPayment={inscription_id:'',type_frais_id:'',montant_attendu:'0',montant_paye:'',mode_paiement:'',date_paiement:new Date().toISOString().slice(0,10),reference_transaction:'',note_caissier:''};
const modeBadge=(mode:string)=>({especes:'bg-slate-100 text-slate-700',orange_money:'bg-orange-100 text-orange-700',wave:'bg-cyan-100 text-cyan-700',mtn_momo:'bg-yellow-100 text-yellow-800',virement:'bg-violet-100 text-violet-700'}[mode]||'bg-slate-100 text-slate-700');
const statusBadge=(s:string)=>({paye:'bg-emerald-100 text-emerald-700',partiel:'bg-orange-100 text-orange-700',annule:'bg-red-100 text-red-700'}[s]||'bg-slate-100 text-slate-700');

export default function FinancesPaiements(){
  const {props}=usePage<{props:FinanceProps}>() as any; const data=props as FinanceProps;
  const [open,setOpen]=useState(false); const [isEdit,setIsEdit]=useState(false); const [editingId,setEditingId]=useState<number|null>(null); const [receipt,setReceipt]=useState<PaymentRow|null>(null); const [cancelTarget,setCancelTarget]=useState<PaymentRow|null>(null);
  const [f,setF]=useState({q:'',classe:'',type:'',mode:'',status:'',period:'all',page:1}); const pageSize=12;
  const form=useForm({...emptyPayment,mode_paiement:data.modesPaiement[0]||'especes'});
  const cancelForm=useForm({motif_annulation:''});
  const selectedEleve=data.eleves.find(e=>String(e.inscription_id)===form.data.inscription_id);
  const currentFee=data.typesFrais.find(fee=>String(fee.id)===form.data.type_frais_id);
  const openCreate=()=>{setIsEdit(false);setEditingId(null);form.reset();form.setData({...emptyPayment,mode_paiement:data.modesPaiement[0]||'especes'});form.clearErrors();setOpen(true);};
  const openEdit=(r:PaymentRow)=>{const fee=data.typesFrais.find(x=>x.id===r.type_frais_id);setIsEdit(true);setEditingId(r.id);form.setData({inscription_id:String(r.inscription_id),type_frais_id:String(r.type_frais_id),montant_attendu:String(fee?.montant||r.montant),montant_paye:String(r.montant),mode_paiement:r.mode||data.modesPaiement[0]||'especes',date_paiement:r.date.split('/').reverse().join('-'),reference_transaction:r.reference||'',note_caissier:r.note_caissier||''});form.clearErrors();setOpen(true);};
  const dejaPaye=useMemo(()=>data.payments.filter(p=>String(p.inscription_id)===form.data.inscription_id&&String(p.type_frais_id)===form.data.type_frais_id&&p.statut!=='annule').reduce((a,b)=>a+b.montant,0),[data.payments,form.data.inscription_id,form.data.type_frais_id]);
  const montantDu=currentFee?.montant||0; const reste=Math.max(0,montantDu-dejaPaye);

  const filtered=useMemo(()=>data.payments.filter(p=>{
    if(f.q&&!`${p.eleve} ${p.reference||''}`.toLowerCase().includes(f.q.toLowerCase()))return false;
    if(f.classe&&p.classe!==f.classe)return false; if(f.type&&p.type_frais!==f.type)return false; if(f.mode&&p.mode!==f.mode)return false; if(f.status&&p.statut!==f.status)return false; return true;
  }),[data.payments,f]);
  const total=filtered.length; const start=(f.page-1)*pageSize; const rows=filtered.slice(start,start+pageSize); const pages=Math.max(1,Math.ceil(total/pageSize));

  return <AppLayout title='Paiements / Encaissements'><div className='space-y-4 bg-[#F8FAFC] p-3 md:p-5'>
    <div className='flex items-center justify-between'><div><h1 className='text-2xl font-bold text-[#0F172A]'>Paiements / Encaissements</h1><p className='text-sm text-[#64748B]'>Enregistrez les paiements des élèves et consultez l’historique des encaissements.</p></div><button onClick={openCreate} className='h-10 rounded-xl bg-blue-600 px-4 text-white hover:bg-blue-700'>Nouveau paiement</button></div>
    <div className='grid gap-3 md:grid-cols-4'>{[['Total encaissé',data.metrics.totalEncaisse],['Encaissements du mois',data.metrics.paiementsDuMois],['Nombre de paiements',data.metrics.nombrePaiements],['Paiements annulés',data.metrics.paiementsAnnules]].map(([l,v])=><div key={String(l)} className='rounded-2xl border border-slate-200 bg-white p-4 shadow-sm'><p className='text-sm text-slate-500'>{l}</p><p className='text-xl font-semibold text-[#0F172A]'>{typeof v==='number'?formatCurrency(v):v}</p></div>)}</div>
    <div className='rounded-2xl border border-slate-200 bg-white p-4 shadow-sm grid gap-2 md:grid-cols-6'><input className='rounded-xl border p-2 text-sm' placeholder='Recherche élève' value={f.q} onChange={e=>setF({...f,q:e.target.value,page:1})}/><select className='rounded-xl border p-2 text-sm' value={f.classe} onChange={e=>setF({...f,classe:e.target.value,page:1})}><option value=''>Classe</option>{data.classes.map(c=><option key={c.id} value={c.nom}>{c.nom}</option>)}</select><select className='rounded-xl border p-2 text-sm' value={f.type} onChange={e=>setF({...f,type:e.target.value,page:1})}><option value=''>Type de frais</option>{data.typesFrais.map(t=><option key={t.id} value={t.libelle}>{t.libelle}</option>)}</select><select className='rounded-xl border p-2 text-sm' value={f.mode} onChange={e=>setF({...f,mode:e.target.value,page:1})}><option value=''>Mode</option>{data.modesPaiement.map(m=><option key={m} value={m}>{m}</option>)}</select><select className='rounded-xl border p-2 text-sm' value={f.status} onChange={e=>setF({...f,status:e.target.value,page:1})}><option value=''>Statut</option><option value='paye'>payé</option><option value='partiel'>partiel</option><option value='annule'>annulé</option><option value='impaye'>en attente</option></select><button className='rounded-xl border p-2 text-sm' onClick={()=>setF({q:'',classe:'',type:'',mode:'',status:'',period:'all',page:1})}>Réinitialiser</button></div>
    <div className='rounded-2xl border border-slate-200 bg-white shadow-sm overflow-auto'><table className='min-w-full text-sm'><thead className='bg-slate-50 text-slate-600'><tr><th className='p-3 text-left'>Date</th><th>Élève</th><th>Classe</th><th>Type de frais</th><th>Montant payé</th><th>Mode</th><th>Référence</th><th>Statut</th><th>Actions</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className='border-t hover:bg-slate-50'><td className='p-3'>{formatDate(r.date)}</td><td>{r.eleve}</td><td>{r.classe}</td><td>{r.type_frais}</td><td>{formatCurrency(r.montant)}</td><td><span className={`rounded-full px-2 py-1 text-xs ${modeBadge(r.mode)}`}>{r.mode}</span></td><td>{r.reference||'Non renseigné'}</td><td><span className={`rounded-full px-2 py-1 text-xs ${statusBadge(r.statut)}`}>{r.statut}</span></td><td><div className='flex gap-2'><button className='text-blue-600' onClick={()=>setReceipt(r)}>Voir reçu</button><button className='text-slate-700 disabled:text-slate-300' disabled={r.statut==='annule'} onClick={()=>openEdit(r)}>Modifier</button><button className='text-red-600 disabled:text-slate-300' disabled={r.statut==='annule'} onClick={()=>setCancelTarget(r)}>Annuler</button></div></td></tr>)}{rows.length===0&&<tr><td className='p-6 text-center text-slate-500' colSpan={9}>{total===0?'Aucune donnée disponible':'Aucun résultat pour ces filtres.'}</td></tr>}</tbody></table></div>
    <div className='flex items-center justify-between text-sm'><p>Affichage de {total?start+1:0} à {Math.min(start+pageSize,total)} sur {total} paiements</p><div className='flex gap-1'><button className='rounded border px-3 py-1' disabled={f.page===1} onClick={()=>setF({...f,page:f.page-1})}>Précédent</button>{Array.from({length:pages}).slice(0,7).map((_,i)=><button key={i} className={`rounded border px-3 py-1 ${f.page===i+1?'bg-blue-600 text-white':''}`} onClick={()=>setF({...f,page:i+1})}>{i+1}</button>)}<button className='rounded border px-3 py-1' disabled={f.page===pages} onClick={()=>setF({...f,page:f.page+1})}>Suivant</button></div></div>

    {open&&<div className='fixed inset-0 z-50 bg-black/30'><div className='ml-auto h-full w-full max-w-xl overflow-y-auto bg-white p-4'><h3 className='text-lg font-semibold'>{isEdit?'Modifier le paiement':'Nouveau paiement'}</h3><div className='grid gap-2 mt-3'><select disabled={isEdit} className='rounded-xl border p-2 disabled:bg-slate-100' value={form.data.inscription_id} onChange={e=>form.setData('inscription_id',e.target.value)}><option value=''>Élève</option>{data.eleves.map(e=><option key={e.inscription_id} value={e.inscription_id}>{e.nom}</option>)}</select><div className='text-sm text-slate-600'>Classe: {selectedEleve?.classe||'Non renseigné'}</div><select disabled={isEdit} className='rounded-xl border p-2 disabled:bg-slate-100' value={form.data.type_frais_id} onChange={e=>{const v=e.target.value; form.setData('type_frais_id',v); const fee=data.typesFrais.find(x=>String(x.id)===v); form.setData('montant_attendu',String(fee?.montant||0));}}><option value=''>Type de frais</option>{data.typesFrais.map(t=><option key={t.id} value={t.id}>{t.libelle}</option>)}</select><div className='text-sm'>Montant dû: {formatCurrency(montantDu)} | Montant déjà payé: {formatCurrency(dejaPaye)} | Reste à payer: {formatCurrency(reste)}</div><input className='rounded-xl border p-2' placeholder='Montant payé' value={form.data.montant_paye} onChange={e=>form.setData('montant_paye',e.target.value)} /><select className='rounded-xl border p-2' value={form.data.mode_paiement} onChange={e=>form.setData('mode_paiement',e.target.value)}>{data.modesPaiement.map(m=><option key={m} value={m}>{m}</option>)}</select><input type='date' className='rounded-xl border p-2' value={form.data.date_paiement} onChange={e=>form.setData('date_paiement',e.target.value)} /><input className='rounded-xl border p-2' placeholder='Référence' value={form.data.reference_transaction} onChange={e=>form.setData('reference_transaction',e.target.value)} /><textarea className='rounded-xl border p-2' placeholder='Observation' value={form.data.note_caissier} onChange={e=>form.setData('note_caissier',e.target.value)} />{Object.keys(form.errors).length>0&&<div className='text-sm text-red-600'>{Object.values(form.errors)[0]}</div>}<div className='flex gap-2'><button className='rounded-xl bg-blue-600 px-4 py-2 text-white' disabled={form.processing||(Number(form.data.montant_paye)>reste&&reste>0)} onClick={()=>{const url=isEdit&&editingId?route('finances.paiements.update',editingId):route('finances.paiements.store'); const method=isEdit&&editingId?form.put:form.post; method(url,{preserveScroll:true,onSuccess:()=>{setOpen(false); setIsEdit(false); setEditingId(null); form.reset(); router.reload({only:['payments','metrics','impayes']});}});}}>{isEdit?'Mettre à jour':'Enregistrer'}</button><button className='rounded-xl border px-4 py-2' onClick={()=>{setOpen(false);setIsEdit(false);setEditingId(null);}}>Fermer</button></div></div></div></div>}
    {receipt&&<div className='fixed inset-0 z-50 grid place-items-center bg-black/30'><div className='w-full max-w-lg rounded-2xl bg-white p-5'><h3 className='text-xl font-bold'>Reçu de paiement</h3><p>Élève: {receipt.eleve}</p><p>Classe: {receipt.classe}</p><p>Type de frais: {receipt.type_frais}</p><p>Montant payé: {formatCurrency(receipt.montant)}</p><p>Mode: {receipt.mode}</p><p>Référence: {receipt.reference||'Non renseigné'}</p><p>Date: {receipt.date}</p><p>Caissier: {receipt.encaisse_par_nom||'Non renseigné'}</p><p>Statut: {receipt.statut}</p><div className='mt-3 flex gap-2'><button onClick={()=>window.print()} className='rounded-xl border px-3 py-2'>Imprimer</button><button disabled className='rounded-xl border px-3 py-2 text-slate-400'>Télécharger PDF</button><button onClick={()=>setReceipt(null)} className='rounded-xl bg-slate-900 px-3 py-2 text-white'>Fermer</button></div></div></div>}
    {cancelTarget&&<div className='fixed inset-0 z-50 grid place-items-center bg-black/30'><div className='w-full max-w-md rounded-2xl bg-white p-5'><p className='font-semibold'>Voulez-vous vraiment annuler ce paiement ? Cette action conservera une trace dans l’historique.</p><textarea className='mt-3 w-full rounded-xl border p-2' placeholder='Motif d’annulation' value={cancelForm.data.motif_annulation} onChange={e=>cancelForm.setData('motif_annulation',e.target.value)} /><div className='mt-3 flex gap-2'><button onClick={()=>setCancelTarget(null)} className='rounded-xl border px-3 py-2'>Fermer</button><button className='rounded-xl bg-red-600 px-3 py-2 text-white' onClick={()=>cancelForm.post(route('finances.paiements.cancel',cancelTarget.id),{preserveScroll:true,onSuccess:()=>{setCancelTarget(null);cancelForm.reset();router.reload({only:['payments','metrics','impayes']});}})}>Confirmer l’annulation</button></div></div></div>}
  </div></AppLayout>
}
