export type FinanceMetrics = {
  totalAttendu:number; totalEncaisse:number; resteAPayer:number; impayesEnCours:number; tauxRecouvrement:number; paiementsDuMois:number; paiementsAnnules:number; nombrePaiements:number;
};
export type PaymentRow = {id:number; date:string; eleve:string; classe:string; montant:number; mode:string; type_frais:string; reference?:string|null; statut:string; inscription_id:number; type_frais_id:number; recu_numero?:string|null; note_caissier?:string|null; motif_annulation?:string|null; encaisse_par_nom?:string|null; justificatif_url?:string|null};
export type ImpayeRow = {inscription_id:number; eleve:string; classe:string; type_frais:string; type_frais_id?:number|null; montant_du:number; montant_paye:number; reste:number; dernier_paiement:string; statut:string; annee_scolaire?:string|null};
export type FinanceProps={depenses?:DepenseRow[]; salaires?:SalaireRow[]; personnel?:Array<{id:number;nom:string;poste:string;salaire_base:number}>; depenseCategories?:string[]; metrics:FinanceMetrics; payments:PaymentRow[]; impayes:ImpayeRow[]; classes:Array<{id:number;nom:string}>; anneesScolaires:Array<{id:number;libelle:string}>; typesFrais:Array<{id:number;libelle:string;montant:number;classe_id?:number|null;annee_scolaire_id?:number|null}>; eleves:Array<{inscription_id:number;eleve_id:number;nom:string;classe:string;classe_id:number}>; modesPaiement:string[]};

export type DepenseRow={id:number;date:string;libelle:string;categorie?:string|null;montant:number;mode_paiement?:string|null;responsable?:string|null;responsable_id?:number|null;justificatif_url?:string|null;statut:string;observation?:string|null};
export type SalaireRow={id:number;personnel_id:number;employe?:string;poste?:string;mois:number;salaire_base:number;primes:number;avances:number;retenues:number;deductions:number;net_a_payer:number;statut:string;date_paiement?:string|null;mode_paiement?:string|null};
